name: blinc_ui_flutter
description: A new Flutter package project.
version: 0.0.1
homepage: https://oneblinc.com/
repository: https://github.com/flutterslayer/blinc_ui_flutter

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: proxima_nova_font
      fonts:
        - asset: assets/fonts/proxima_nova_font.otf

